//must set in cookies or localStorage
export const USER_TOKENS = {
  accessToken:
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZXMiOlsibW9iaWxlX3YyIiwibW9iaWxlX3YxIiwid2VidmlldyJdLCJreWMiOjAsInVzZXJDb2RlIjpudWxsLCJzdWJzaWR5IjowLCJ1ZGlkIjpudWxsLCJhdWQiOiJzbmFwcGZvb2RfcHdhIiwiZXhwIjoxNzEzMjkxMDQzLCJuYmYiOjE3MTMwMzE3MjMsImlhdCI6MTcxMzAzMTcyMywianRpIjoiZmI3YjVlOGMtNWE0Zi00YWNiLWI2YjMtODAxOGE1N2YzMTc2Iiwic3ViIjoiIn0.kyl1kWwn3adjSgQnRg1JX1dCwyc-",
  refreshToken:
    "gntCaZ10mbqwHJSDpjJXzJclUQqe2UftBCOEgXycJyooqs4cCej53WZDvRXu5j0BAYQU8w1vdX0lp5eWGdAbSanyai9_EYe7iKabcPtx8nxStoRie5vDjy6LvGUAKzBHVwqKHguhZcOujCXFU9g3SGKUoGmVKyeU3YYYjwH010HJV7dtsr0KLc31nPZY7OCkBYbtdN7DfyIH9YMKWtFpzkDuGj-NA4q2wT1t6W_kIVzsaJU9OzC4VHgez3WKHV0Syd4LkKgyni_HyATUtOkIRwKTKOSM8f0E6EXSPZZrf8JYAZbEfmAC4NmqSA",
};
